version: '3.8'

services:
  # PostgreSQL Database
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-project_management}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-project_management}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    labels:
      - "service=database"
      - "type=postgres"

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-mongoadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongopass}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-task_service}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init-scripts:/docker-entrypoint-initdb.d
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    labels:
      - "service=database"
      - "type=mongodb"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispass}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    labels:
      - "service=cache"
      - "type=redis"

  # User Service
  user-service:
    build:
      context: .
      dockerfile: services/Dockerfile
      target: user-service
      args:
        - BUILD_ENV=${BUILD_ENV:-production}
    container_name: user-service
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-secret}@postgres-db:5432/${POSTGRES_DB:-project_management}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - USER_SERVICE_URL=http://user-service:8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
      - REDIS_TTL=3600
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    ports:
      - "8000:8000"
    volumes:
      - ./services/user_service:/app/user_service
      - ./services/utils:/app/utils
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    labels:
      - "service=application"
      - "type=user-service"

  # Project Service
  project-service:
    build:
      context: .
      dockerfile: services/Dockerfile
      target: project-service
      args:
        - BUILD_ENV=${BUILD_ENV:-production}
    container_name: project-service
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-secret}@postgres-db:5432/${POSTGRES_DB:-project_management}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - USER_SERVICE_URL=http://user-service:8000
      - PROJECT_SERVICE_URL=http://project-service:8001
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    ports:
      - "8001:8001"
    volumes:
      - ./services/project_service:/app/project_service
      - ./services/utils:/app/utils
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    depends_on:
      postgres-db:
        condition: service_healthy
      user-service:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    labels:
      - "service=application"
      - "type=project-service"

  # Task Service
  task-service:
    build:
      context: .
      dockerfile: services/Dockerfile
      target: task-service
      args:
        - BUILD_ENV=${BUILD_ENV:-production}
    container_name: task-service
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-secret}@postgres-db:5432/${POSTGRES_DB:-project_management}
      - MONGODB_URL=mongodb://${MONGO_USER:-mongoadmin}:${MONGO_PASSWORD:-mongopass}@mongodb:27017/${MONGO_DB:-task_service}?authSource=admin
      - MONGODB_DB_NAME=${MONGO_DB:-task_service}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - USER_SERVICE_URL=http://user-service:8000
      - PROJECT_SERVICE_URL=http://project-service:8001
      - TASK_SERVICE_URL=http://task-service:8002
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    ports:
      - "8002:8002"
    volumes:
      - ./services/task_service:/app/task_service
      - ./services/utils:/app/utils
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network
    depends_on:
      postgres-db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      user-service:
        condition: service_started
      project-service:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    labels:
      - "service=application"
      - "type=task-service"

networks:
  app-network:
    driver: bridge
    name: project-management-network
    labels:
      - "project=project-management-system"

volumes:
  postgres_data:
    name: project-management-postgres-data
    labels:
      - "type=postgres"
      - "data=persistent"
  mongo_data:
    name: project-management-mongo-data
    labels:
      - "type=mongodb"
      - "data=persistent"
  redis_data:
    name: project-management-redis-data
    labels:
      - "type=redis"
      - "data=persistent"